# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
	pod 'PhoneNumberKit', :path => '/Users/prasenjitdasgupta/Documents/Pod_Project/Git_Projects/PhoneNumberKit'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
